/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfileBound {
    'index': number;
  }
  interface AppProfileBoundAttributes extends StencilHTMLAttributes {
    'index'?: number;
  }

  interface AppProfileSimple {
    'index': number;
  }
  interface AppProfileSimpleAttributes extends StencilHTMLAttributes {
    'index'?: number;
  }

  interface AppProfile {
    'index': number;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'index'?: number;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfileBound': Components.AppProfileBound;
    'AppProfileSimple': Components.AppProfileSimple;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile-bound': Components.AppProfileBoundAttributes;
    'app-profile-simple': Components.AppProfileSimpleAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileBoundElement extends Components.AppProfileBound, HTMLStencilElement {}
  var HTMLAppProfileBoundElement: {
    prototype: HTMLAppProfileBoundElement;
    new (): HTMLAppProfileBoundElement;
  };

  interface HTMLAppProfileSimpleElement extends Components.AppProfileSimple, HTMLStencilElement {}
  var HTMLAppProfileSimpleElement: {
    prototype: HTMLAppProfileSimpleElement;
    new (): HTMLAppProfileSimpleElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile-bound': HTMLAppProfileBoundElement
    'app-profile-simple': HTMLAppProfileSimpleElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile-bound': HTMLAppProfileBoundElement;
    'app-profile-simple': HTMLAppProfileSimpleElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
